version: "3.7"

services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
      target: local
      args:
        USERID: ${USERID:-1000}
        GROUPID: ${GROUPID:-1000}
    volumes:
      - .:/var/www:delegated
    ports:
      - '8080:80'
